package org.bian.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.bian.dto.BQInitiativeCreateInputModelBQInitiativeInstanceRecordDateType;

import javax.validation.Valid;
  
/**
 * BQInitiativeCaptureInputModelBQInitiativeInstanceRecord
 */
public class BQInitiativeCaptureInputModelBQInitiativeInstanceRecord   {
  private String segmentInitiativeSchedule = null;

  private String segmentInitiativeWorkProducts = null;

  private String documentDirectoryEntryInstanceReference = null;

  private String correspondenceInstanceReference = null;

  private BQInitiativeCreateInputModelBQInitiativeInstanceRecordDateType dateType = null;


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Planned and actual dates for activities making up the initiative. Any necessary details describing the purpose or reference properties of the transaction 
   * @return segmentInitiativeSchedule
  **/

  public String getSegmentInitiativeSchedule() {
    return segmentInitiativeSchedule;
  }

  public void setSegmentInitiativeSchedule(String segmentInitiativeSchedule) {
    this.segmentInitiativeSchedule = segmentInitiativeSchedule;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: File of consolidated notes, assessments etc. arising from the work 
   * @return segmentInitiativeWorkProducts
  **/

  public String getSegmentInitiativeWorkProducts() {
    return segmentInitiativeWorkProducts;
  }

  public void setSegmentInitiativeWorkProducts(String segmentInitiativeWorkProducts) {
    this.segmentInitiativeWorkProducts = segmentInitiativeWorkProducts;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to associated documents (when appropriate) 
   * @return documentDirectoryEntryInstanceReference
  **/

  public String getDocumentDirectoryEntryInstanceReference() {
    return documentDirectoryEntryInstanceReference;
  }

  public void setDocumentDirectoryEntryInstanceReference(String documentDirectoryEntryInstanceReference) {
    this.documentDirectoryEntryInstanceReference = documentDirectoryEntryInstanceReference;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the correspondence generated by the initiative 
   * @return correspondenceInstanceReference
  **/

  public String getCorrespondenceInstanceReference() {
    return correspondenceInstanceReference;
  }

  public void setCorrespondenceInstanceReference(String correspondenceInstanceReference) {
    this.correspondenceInstanceReference = correspondenceInstanceReference;
  }


  /**
   * Get dateType
   * @return dateType
  **/

  public BQInitiativeCreateInputModelBQInitiativeInstanceRecordDateType getDateType() {
    return dateType;
  }

  public void setDateType(BQInitiativeCreateInputModelBQInitiativeInstanceRecordDateType dateType) {
    this.dateType = dateType;
  }


}

